### ISSUE TITLE
不知道有没有人在用 gistbox, 可以整合一个 group 到laravelso

### ISSUE THREAD

**Issue by RryLee** [laravelso/site#10]

**Comment by RryLee** [comment]
http://www.gistboxapp.com/

**Comment by overtrue** [comment]
不知道你说的整合是指怎么玩？

**Comment by RryLee** [comment]
没表达清楚，就是在 gistbox 上建一个group，然后放在laravelso上宣传

**Comment by overtrue** [comment]
gistbox 是基于 GitHub 的 gist 的啊，你的意思是建立一个 laravelso 的组织？

**Comment by RryLee** [comment]
是的。。。gist国内不好用，但是gistbox没什么问题

**Comment by overtrue** [comment]
@RryLee 可是这个东西用法与我们网站关系不大啊

**Comment by RryLee** [comment]
好吧，可以这样认为，一般只是减一些不熟悉的片段。

**Comment by yoooong** [comment]
这site是没有后台管理的吗

**Comment by RryLee** [comment]
貌似没有

**Comment by breeze323136** [comment]
请问一下vendor库哪去呢？我按照readme.md安装有问题，很多类库都不见了，如执行php composer.phar install -vvv：Key post-update-cmd is a duplicate in ./composer.json at line 50

 [Composer\Downloader\TransportException]
  The "http://packagist.org/p/provider-2015-10%243c6a08c58ee38b750b1e6c74047a82f65509b885976ee7948d8b8ba60c559130.json" file could not be downloaded: f
  ailed to open stream: HTTP request failed!


Exception trace:
 () at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Util/RemoteFilesystem.php:307
 Composer\Util\RemoteFilesystem->get() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Util/RemoteFilesystem.php:84
 Composer\Util\RemoteFilesystem->getContents() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Repository/ComposerRepository.php:609
 Composer\Repository\ComposerRepository->fetchFile() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Repository/ComposerRepository.php:511
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Repository/ComposerRepository.php:280
 Composer\Repository\ComposerRepository->whatProvides() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Installer.php:523
 Composer\Installer->doInstall() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///Users/liangfeng/Code/site/composer.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///Users/liangfeng/Code/site/composer.phar/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/liangfeng/Code/site/composer.phar/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///Users/liangfeng/Code/site/composer.phar/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///Users/liangfeng/Code/site/composer.phar/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///Users/liangfeng/Code/site/composer.phar/bin/composer:43
 require() at /Users/liangfeng/Code/site/composer.phar:25

**Comment by overtrue** [comment]
@breeze323136 请翻墙
