### ISSUE TITLE
没找到Model目录

### ISSUE THREAD

**Issue by royeedai** [laravelso/site#14]
导致app\model  相关的都报错，

**Comment by overtrue** [comment]
@RoyeeDai 哪里用到了app\model ?

**Comment by RoyeeDai** [comment]
ReflectionException in Container.php line 795:
Class App\Models\Link does not exist

2,后台有标签管理，但是
InvalidArgumentException in FileViewFinder.php line 137:
View [admin.tags.list] not found.

我看了下是没看到tags目录。是要配置什么吗？

**Comment by overtrue** [comment]
你这是访问哪个地方来的啊？访问后台？这个应用没写后台

**Comment by royeedai** [comment]
哦。。。知道了，3q。。。
