### ISSUE TITLE
关于分类标签问题

### ISSUE THREAD

**Issue by janily** [laravelso/site#19]
hello
你好，我想问下，我把网站clone到本地并且运行起来后，发现在新建文章后，怎么添加新的分类和标签呢？使用admin帐号登录，也没看到相关设置的选项。
谢谢。

**Comment by overtrue** [comment]
@janily 目前没有做后台

**Comment by overtrue** [comment]
直接在数据库加

**Comment by janily** [comment]
我现在是直接在数据库加的，谢谢哈，我现在准备用你的这个源码做了个网站。
