### ISSUE TITLE
遇到点小问题

### ISSUE THREAD

**Issue by iralance** [laravelso/site#6]
首先 安装环境必须是php>=5.6
然后composer install 需要开启几个扩展
我在访问的时候出了点问题，麻烦能帮忙看下么。。
ErrorException in Filesystem.php line 81:
file_put_contents(/69abd0d52d3979bdb833e79f766eb53d): failed to open stream: Permission denied
项目目录下 storage已经给chmod -R 755权限了。这个错误为何会写到根目录？求解

**Comment by overtrue** [comment]
@iralance 写根目录是框架找不到可写目录才这样的，确实需要php5.6，因为我用了一些新的语法。

**Comment by iralance** [comment]
像前辈学习。。
